#!/usr/bin/env python3
import string
from genPassword_args import Args
import pyperclip
import random

VERSION = "1.0.0"
def version(version) -> str: 
    print(f"""genPassword v{version}
    \r\nCreated by @Tr4shL0rd""")
    exit()
def char_list() -> list:
    CHAR_LIST_LETTER           = list(string.ascii_letters)
    CHAR_LIST_LETTER_LOWERCASE = list(string.ascii_lowercase)
    CHAR_LIST_LETTER_UPPERCASE = list(string.ascii_uppercase)
    CHAR_LIST_DIGITS           = list(string.digits)
    CHAR_LIST_SYMBOLS          = ["*","!","#","%","$","^","@","&"]
    CHAR_LIST_ALL = list(CHAR_LIST_LETTER)+list(CHAR_LIST_LETTER_LOWERCASE)+list(CHAR_LIST_LETTER_UPPERCASE)+list(CHAR_LIST_DIGITS)+list(CHAR_LIST_SYMBOLS)
    char_list_ref = [CHAR_LIST_LETTER,CHAR_LIST_LETTER_LOWERCASE,CHAR_LIST_LETTER_UPPERCASE,CHAR_LIST_DIGITS,CHAR_LIST_SYMBOLS]

    bad_symbols = ["0", "o", "i", "l", "1"]
    for char_list in char_list_ref:
        for symbol in bad_symbols:
            if symbol in char_list:
                char_list.remove(symbol)

    return (CHAR_LIST_LETTER, CHAR_LIST_LETTER_LOWERCASE, CHAR_LIST_LETTER_UPPERCASE, CHAR_LIST_DIGITS, CHAR_LIST_SYMBOLS, CHAR_LIST_ALL)   

def case_match(args):
    CHAR_LETTER, CHAR_LETTER_LOWER, CHAR_LETTER_UPPER, CHAR_DIGITS,CHAR_SYMBOLS,CHAR_ALL = char_list()
    available_cases = """Available Cases:\
                \n\tall(default)\
                \n\tfull\
                \n\tlower\
                \n\tupper\
                \n\tdigits\
                \n\tsymbols\
                """

    match args.case:
            case "all":
                used_char_list = CHAR_ALL
            case "full":
                used_char_list = CHAR_LETTER
            case "lower":
                used_char_list = CHAR_LETTER_LOWER
            case "upper":
                used_char_list = CHAR_LETTER_UPPER
            case "digits":
                used_char_list = CHAR_DIGITS
            case "symbols":
                used_char_list = CHAR_SYMBOLS
            case "help":
                return available_cases
            case _:
                return f"Case \"{args.case}\" is not recognized\n{available_cases}"
    return used_char_list
def main():
    args = Args().pwrd_args()
    used_char_list = case_match(args)
    password = "".join(random.sample(used_char_list, args.pass_length))
    if args.version:
        version(VERSION)
    if args.clip:
        pyperclip.copy(password)
    return f"password: {password}"


print(main())
